# Generated by Django 3.2.3 on 2021-05-26 21:14

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0003_auto_20210526_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
    ]
