# Generated by Django 3.2.3 on 2021-06-01 15:46

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0004_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0,
                                                   verbose_name='Позиция фото'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True,
                                           verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True,
                                   verbose_name='Сокращенное описание'),
        ),
    ]
